create table USER_LOGIN_INFO (ID INTEGER PRIMARY KEY,USER_ID VARCHAR(20),
					USER_NAME VARCHAR(20),
					PASSWORD VARCHAR(20),STATUS VARCHAR(1),
					CREATED_BY VARCHAR(10),CREATED_DATE TIMESTAMP,
					MODIFIED_BY VARCHAR(10),MODIFIED_DATE TIMESTAMP,
					FAILURE_COUNT INTEGER,IS_ACCOUNT_LOCKED varchar(1),
					LAST_LOGGEDIN_DATE TIMESTAMP,LAST_PASSWORD_RESET_DATE TIMESTAMP,
					PASSWORD_RESET_TOKEN VARCHAR(25));
					
CREATE TABLE USER_DETAIL (USER_ID VARCHAR(25) PRIMARY KEY,
					FIRST_NAME VARCHAR(20),LAST_NAME VARCHAR(20),
					MOBILE_NUMBER  VARCHAR(20),EMAIL_ID  VARCHAR(25),
					ADDRESS_ID INTEGER,STATUS VARCHAR(1),
					CREATED_BY VARCHAR(10),CREATED_DATE TIMESTAMP,
					MODIFIED_BY VARCHAR(10),MODIFIED_DATE TIMESTAMP);

CREATE TABLE ADDRESS (ID INTEGER PRIMARY KEY,ADDRESS_LINE1 VARCHAR(50),
					ADDRESS_LINE2 VARCHAR(50),CITY  VARCHAR(20)
					STATE  VARCHAR(20),PINCODE  VARCHAR(6),STATUS VARCHAR(1),
					CREATED_BY VARCHAR(10),CREATED_DATE TIMESTAMP,
					MODIFIED_BY VARCHAR(10),MODIFIED_DATE TIMESTAMP
					);
CREATE TABLE USER_ROLE (ID INTEGER PRIMARY KEY,USER_ID VARCHAR(20),
					USER_ROLE VARCHAR(10),STATUS VARCHAR(1),
					CREATED_BY VARCHAR(10),CREATED_DATE TIMESTAMP,
					MODIFIED_BY VARCHAR(10),MODIFIED_DATE TIMESTAMP
					);					
CREATE TABLE CATEGORY (ID INTEGER PRIMARY KEY,NAME VARCHAR(50),
					STATUS VARCHAR(1),
					CREATED_BY VARCHAR(10),CREATED_DATE TIMESTAMP,
					MODIFIED_BY VARCHAR(10),MODIFIED_DATE TIMESTAMP
					);					
CREATE TABLE PRODUCT (ID INTEGER PRIMARY KEY,PRODUCT_CODE VARCHAR(20),
					NAME VARCHAR(50),CATEGORY_ID INTEGER,
					PRICE DOUBLE,DISCOUNT DOUBLE,
					IMAGE_ID VARCHAR,QUANTITY INTEGER
					STATUS VARCHAR(1),
					CREATED_BY VARCHAR(10),CREATED_DATE TIMESTAMP,
					MODIFIED_BY VARCHAR(10),MODIFIED_DATE TIMESTAMP
					);
