create table F_USER (ID INTEGER PRIMARY KEY,USER_NAME VARCHAR(20),
					PASSWORD VARCHAR(20),EMAILID VARCHAR(20),
					CREATED_BY VARCHAR(10),CREATED_DATE DATE,
					MODIFIED_BY VARCHAR(10),MODIFIED_DATE DATE);