create table USER_LOGIN_INFO (ID INTEGER PRIMARY KEY,USER_ID VARCHAR(20),
					USER_NAME VARCHAR(20),
					PASSWORD VARCHAR(20),STATUS VARCHAR(1),
					CREATED_BY VARCHAR(10),CREATED_DATE TIMESTAMP,
					MODIFIED_BY VARCHAR(10),MODIFIED_DATE TIMESTAMP,
					FAILURE_COUNT INTEGER,IS_ACCOUNT_LOCKED varchar(1),
					LAST_LOGGEDIN_DATE TIMESTAMP,LAST_PASSWORD_RESET_DATE TIMESTAMP,
					PASSWORD_RESET_TOKEN VARCHAR(25));
					
CREATE TABLE USER_DETAIL (USER_ID VARCHAR(25) PRIMARY KEY,
					FIRST_NAME VARCHAR(20),LAST_NAME VARCHAR(20),
					MOBILE_NUMBER  VARCHAR(20),EMAIL_ID  VARCHAR(25),
					ADDRESS_ID INTEGER,STATUS VARCHAR(1),
					CREATED_BY VARCHAR(10),CREATED_DATE TIMESTAMP,
					MODIFIED_BY VARCHAR(10),MODIFIED_DATE TIMESTAMP);
					